[package]
authors = ["Axel Habermaier <axelhabermaier@gmail.com>"]
edition = "2018"
name = "orbs"
version = "0.1.0"

[dependencies]
winapi = {version = "0.3", features = [
  "impl-default",
  "winbase",
  "d3d11",
  "winuser",
  "wincon",
]}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
