use num_enum::TryFromPrimitive;
use winapi::um::winuser::*;

#[derive(Debug, TryFromPrimitive)]
#[repr(i32)]
pub enum MouseButton {
    Left,
    Right,
    Middle,
    XButton1,
    XButton2,
}

#[derive(Debug, TryFromPrimitive)]
#[repr(i32)]
pub enum Key {
    NumpadEnter,
    Num0 = 0x30,
    Num1 = 0x31,
    Num2 = 0x32,
    Num3 = 0x33,
    Num4 = 0x34,
    Num5 = 0x35,
    Num6 = 0x36,
    Num7 = 0x37,
    Num8 = 0x38,
    Num9 = 0x39,
    A = 0x41,
    B = 0x42,
    C = 0x43,
    D = 0x44,
    E = 0x45,
    F = 0x46,
    G = 0x47,
    H = 0x48,
    I = 0x49,
    J = 0x4A,
    K = 0x4B,
    L = 0x4C,
    M = 0x4D,
    N = 0x4E,
    O = 0x4F,
    P = 0x50,
    Q = 0x51,
    R = 0x52,
    S = 0x53,
    T = 0x54,
    U = 0x55,
    V = 0x56,
    W = 0x57,
    X = 0x58,
    Y = 0x59,
    Z = 0x5A,
    BackSlash2 = VK_OEM_102,
    Scroll = VK_SCROLL,
    Print = VK_SNAPSHOT,
    NumLock = VK_NUMLOCK,
    NumpadDecimal = VK_DECIMAL,
    LeftShift = VK_LSHIFT,
    RightShift = VK_RSHIFT,
    LeftSystem = VK_LWIN,
    RightSystem = VK_RWIN,
    Menu = VK_APPS,
    Semicolon = VK_OEM_1,
    Slash = VK_OEM_2,
    Equal = VK_OEM_PLUS,
    Dash = VK_OEM_MINUS,
    LeftBracket = VK_OEM_4,
    RightBracket = VK_OEM_6,
    Comma = VK_OEM_COMMA,
    Period = VK_OEM_PERIOD,
    Quote = VK_OEM_7,
    BackSlash = VK_OEM_5,
    Grave = VK_OEM_3,
    Escape = VK_ESCAPE,
    Space = VK_SPACE,
    Return = VK_RETURN,
    Back = VK_BACK,
    Tab = VK_TAB,
    PageUp = VK_PRIOR,
    PageDown = VK_NEXT,
    End = VK_END,
    Home = VK_HOME,
    Insert = VK_INSERT,
    Delete = VK_DELETE,
    Add = VK_ADD,
    Subtract = VK_SUBTRACT,
    Multiply = VK_MULTIPLY,
    Divide = VK_DIVIDE,
    Pause = VK_PAUSE,
    F1 = VK_F1,
    F2 = VK_F2,
    F3 = VK_F3,
    F4 = VK_F4,
    F5 = VK_F5,
    F6 = VK_F6,
    F7 = VK_F7,
    F8 = VK_F8,
    F9 = VK_F9,
    F10 = VK_F10,
    F11 = VK_F11,
    F12 = VK_F12,
    F13 = VK_F13,
    F14 = VK_F14,
    F15 = VK_F15,
    Left = VK_LEFT,
    Right = VK_RIGHT,
    Up = VK_UP,
    Down = VK_DOWN,
    CapsLock = VK_CAPITAL,
    Numpad0 = VK_NUMPAD0,
    Numpad1 = VK_NUMPAD1,
    Numpad2 = VK_NUMPAD2,
    Numpad3 = VK_NUMPAD3,
    Numpad4 = VK_NUMPAD4,
    Numpad5 = VK_NUMPAD5,
    Numpad6 = VK_NUMPAD6,
    Numpad7 = VK_NUMPAD7,
    Numpad8 = VK_NUMPAD8,
    Numpad9 = VK_NUMPAD9,
    RightControl = VK_RCONTROL,
    LeftControl = VK_LCONTROL,
    RightAlt = VK_RMENU,
    LeftAlt = VK_LMENU,
}
